export const ACTION_SIGNIN = 'SIGNIN'
export const ACTION_SIGNUP = 'SIGNUP'
export const ACTION_SIGNIN_ERROR = 'SIGNIN_ERROR'
export const ACTION_SIGNUP_ERROR = 'SIGNUP_ERROR'

export const ACTION_CONTENT_SWITCH = 'CONTENT_SWITCH'

export const ACTION_COMPETITION_SWITCH = 'COMPETITION_SWITCH'
export const ACTION_COMPETITION_CREATE = 'COMPETITION_CREATE'
